added custom flipview for jithub's showcase
UWPCommunity/launch-showcase pull request #7
Opened 2021-08-29 03:18 UTC by nerocui

2021-08-29 22:55 UTC, Arlodotexe approved these changes

2021-08-30 00:26 UTC, Arlodotexe requested changes

2021-08-30 00:26 UTC, Arlodotexe commented on LaunchShowcase.Shared/LaunchShowcase.Shared.projitems
> -    <Compile Include="$(MSBuildThisFileDirectory)Themes\ShowcaseTemplates\FluentStoreControl.xaml.cs">
Looks like you accidentally overwrote some code needed for another template page, causing builds on this branch to fail. Could you please fix this?

2021-08-30 01:15 UTC, nerocui commented
Opened another one without the conflict.

2021-08-30 01:15 UTC, closed without merging